version: '3'

services:

  php:
    build: ./docker/php
    volumes:
      - './project:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './project:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  db: # Laravel .env DB_HOST=db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=8M # increase dump size limit if necessary



