version: '3.1'

# Collect 3 services to one project (container)

services:
  # add php & apache from Dockerfile ( . it's  mean current dir where locates Dockerfile)
  php:
    build: .
    ports:
      - 8081:80

  # the image took from Docker hub
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  # the image took from Docker hub
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


# build command: docker-compose build
# run command: docker-compose up